// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTNMhbK_ysc_COoVwVTy_LvLd-2i_TQ4M',
    appId: '1:287820568101:web:f6b30aaaa66e57981591cc',
    messagingSenderId: '287820568101',
    projectId: 'tugtugan-74f45',
    authDomain: 'tugtugan-74f45.firebaseapp.com',
    storageBucket: 'tugtugan-74f45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjZ3JZVn92wj6K4X8f8-bIn8A3JiWD6N8',
    appId: '1:287820568101:android:5b05d645629aad941591cc',
    messagingSenderId: '287820568101',
    projectId: 'tugtugan-74f45',
    storageBucket: 'tugtugan-74f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJHGthDkUPj_HP1A5Q1wVNKlNNUCIiMWk',
    appId: '1:287820568101:ios:2320f694bbd5d19a1591cc',
    messagingSenderId: '287820568101',
    projectId: 'tugtugan-74f45',
    storageBucket: 'tugtugan-74f45.firebasestorage.app',
    iosBundleId: 'com.tristans.tugtugan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJHGthDkUPj_HP1A5Q1wVNKlNNUCIiMWk',
    appId: '1:287820568101:ios:2320f694bbd5d19a1591cc',
    messagingSenderId: '287820568101',
    projectId: 'tugtugan-74f45',
    storageBucket: 'tugtugan-74f45.firebasestorage.app',
    iosBundleId: 'com.tristans.tugtugan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTNMhbK_ysc_COoVwVTy_LvLd-2i_TQ4M',
    appId: '1:287820568101:web:49a5ac7179a140341591cc',
    messagingSenderId: '287820568101',
    projectId: 'tugtugan-74f45',
    authDomain: 'tugtugan-74f45.firebaseapp.com',
    storageBucket: 'tugtugan-74f45.firebasestorage.app',
  );
}
