name: tugtugan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  loading_animation_widget: ^1.3.0
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.6
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.2
  mapbox_maps_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  location: ^7.0.1
  go_router: ^15.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
    - .env
