// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPDElpq_SyChJFtame_KFXM3phW7x19FQ',
    appId: '1:766765293741:web:4ed693d399ec452dbee624',
    messagingSenderId: '766765293741',
    projectId: 'tugtugan-dev',
    authDomain: 'tugtugan-dev.firebaseapp.com',
    storageBucket: 'tugtugan-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqqsT8W2XmuKz3CnOArxMeL2WftOWfJQ',
    appId: '1:766765293741:android:dd1dcc56bd205c24bee624',
    messagingSenderId: '766765293741',
    projectId: 'tugtugan-dev',
    storageBucket: 'tugtugan-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlS4sdfycQTgrgj8IxO5_uZ378F8K8os',
    appId: '1:766765293741:ios:206789c8bbd1de6cbee624',
    messagingSenderId: '766765293741',
    projectId: 'tugtugan-dev',
    storageBucket: 'tugtugan-dev.firebasestorage.app',
    iosBundleId: 'com.tristans.tugtugan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlS4sdfycQTgrgj8IxO5_uZ378F8K8os',
    appId: '1:766765293741:ios:206789c8bbd1de6cbee624',
    messagingSenderId: '766765293741',
    projectId: 'tugtugan-dev',
    storageBucket: 'tugtugan-dev.firebasestorage.app',
    iosBundleId: 'com.tristans.tugtugan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPDElpq_SyChJFtame_KFXM3phW7x19FQ',
    appId: '1:766765293741:web:fc9a49aa759ab23bbee624',
    messagingSenderId: '766765293741',
    projectId: 'tugtugan-dev',
    authDomain: 'tugtugan-dev.firebaseapp.com',
    storageBucket: 'tugtugan-dev.firebasestorage.app',
  );
}
